// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Doc = Collections['docs']['schema']['_output']
export declare const docs: Doc[]

export type Post = Collections['blog']['schema']['_output']
export declare const blog: Post[]

export type ArchiveEvent = Collections['archive']['schema']['_output']
export declare const archive: ArchiveEvent[]
